os: linux
dist: bionic
services:
  - docker
language: generic

env:
  - ROS_DISTRO=kinetic
  - ROS_DISTRO=melodic

before_script:
  - docker pull ros:${ROS_DISTRO}-ros-core

script:
  - docker run --rm -v $(pwd):/package_ws/src/staleness_test --env=ROS_DISTRO ros:${ROS_DISTRO}-ros-core /package_ws/src/staleness_test/docker_scripts/build_and_run.sh
